import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import http from 'node:http';
import { GROUPS, DEFAULT_CODES, risk, days, today } from '../capability-core.mjs';
import { createCapabilityService } from '../capability-service.mjs';
import { seedCapabilityFixture } from './capability-fixture.mjs';

const tmp=await fs.mkdtemp(path.join(os.tmpdir(),'capability-integration-'));
Object.assign(process.env,{NODE_ENV:'test',MUC_NO_LISTEN:'1',DATABASE_URL:'',DB_PATH:path.join(tmp,'test.sqlite'),UPLOAD_DIR:path.join(tmp,'uploads')});
const {route,db,capabilityService:service}=await import('../server.mjs');
const {workspace,data}=await seedCapabilityFixture(db,process.env.CAPABILITY_BASELINE);
service.syncMaster();
const server=http.createServer(route);
await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
const base='http://127.0.0.1:'+server.address().port;
let cookie='';
async function api(url,body,expected=200){
  const response=await fetch(base+'/api/'+url,{method:body?'POST':'GET',headers:{origin:base,...(cookie?{cookie}:{}),...(body?{'content-type':'application/json'}:{})},body:body?JSON.stringify(body):undefined});
  const value=await response.json();assert.equal(response.status,expected,JSON.stringify(value));return {value,response};
}
const suffix='?workspace='+encodeURIComponent(workspace);
const snapshot=async()=>(await api('capability/snapshot'+suffix)).value;
let actor;
async function cmd(operation,payload={},expected=200){const s=await snapshot();return (await api('capability/commands'+suffix,{operation,revision:s.revision,requestId:crypto.randomUUID(),...payload},expected)).value;}
try{
  const html=await (await fetch(base+'/')).text();
  assert.equal((html.match(/id="personnelPage"/g)||[]).length,1);
  assert.equal((html.match(/id="capabilityHost"/g)||[]).length,1);
  const asset=await fetch(base+'/capability/module.js');assert.equal(asset.status,200);assert.match(asset.headers.get('content-type'),/javascript/);
  assert.ok((await asset.text()).includes('mountCapability'));
  await api('capability/snapshot'+suffix,undefined,401);
  const login=await api('login',{username:'54002010',password:'muc2026'});
  cookie=login.response.headers.get('set-cookie').split(';')[0];actor=login.value.user;
  assert.ok(Number.isInteger(service.nonParticipants(actor).cadre));
  assert.ok(!service.organizationIssues(actor).some(item=>item.employeeNo==='54002010'));
  let s=await snapshot();
  assert.equal(s.people.length,data.people.length);
  assert.equal(s.capabilityVersion,s.revision);assert.ok(Number.isInteger(s.masterDataVersion));assert.equal(s.dataVersion,`${s.masterDataVersion}:${s.capabilityVersion}`);
  assert.equal(db.prepare('select source_marker from capability_meta where id=1').get().source_marker,'center-master-v1');
  const initial=structuredClone(s);
  if(process.env.CAPABILITY_BASELINE){
    assert.equal(s.people.length,134);
    assert.deepEqual(GROUPS.map(g=>s.stats[g].administrative.length),[28,31,31,31]);
    for(const [code,counts] of [
      [DEFAULT_CODES[0],[14,18,16,20]],[DEFAULT_CODES[1],[15,18,16,21]],
      [DEFAULT_CODES[2],[14,13,14,12]],[DEFAULT_CODES[3],[13,13,14,11]],
      [DEFAULT_CODES[4],[0,2,2,1]],[DEFAULT_CODES[5],[2,1,1,1]]
    ]) assert.deepEqual(GROUPS.map(g=>s.matrix.find(p=>p.code===code).actual[g].length),counts,code);
    assert.deepEqual(GROUPS.map(g=>s.matrix.find(p=>p.code==='2-A03-01').actual[g].length),[3,3,5,5]);
    assert.equal(s.matrix.filter(p=>p.code==='2-A03-01').length,1);
  }
  assert.equal(risk(0,0),'good');assert.equal(risk(1,2),'warning');assert.equal(risk(1,3),'danger');assert.equal(risk(0,1),'danger');
  assert.equal(days('2026-08-01','2026-08-02'),2);assert.equal(days(null),null);
  const specialGroup=db.prepare("select * from organization_units where code='GROUP-LINE-SPECIAL'").get();
  const specialPersonId='cap-special-person',specialEmployeeNo='78999999',at=new Date().toISOString(),beforeSpecial=s;
  db.prepare('insert into personnel(id,employee_no,name,department,home_team,department_id,personnel_group_id,administrative_team_id,employment_status,data_status,created_at,updated_at) values(?,?,?,?,?,?,?,?,?,?,?,?)').run(specialPersonId,specialEmployeeNo,'特殊班组回归人员','航线维修车间','',specialGroup.parent_id,specialGroup.id,null,'在职','active',at,at);
  service.syncMaster();s=await snapshot();
  const specialPerson=s.people.find(p=>p.id===specialPersonId);
  assert.equal(specialPerson.personnelGroupCode,'GROUP-LINE-SPECIAL');assert.equal(specialPerson.administrativeGroup,null);assert.equal(specialPerson.administrativeUnit,'特殊班组');assert.equal(s.states.find(state=>state.personId===specialPersonId).workingGroup,null);
  assert.deepEqual(GROUPS.map(group=>s.stats[group].actual.length),GROUPS.map(group=>beforeSpecial.stats[group].actual.length));
  assert.deepEqual(GROUPS.map(group=>s.stats[group].administrative.length),GROUPS.map(group=>beforeSpecial.stats[group].administrative.length));
  await cmd('move',{personId:specialPersonId,targetGroup:'一组'});s=await snapshot();assert.equal(s.stats['一组'].actual.length,beforeSpecial.stats['一组'].actual.length+1);assert.equal(s.stats['一组'].administrative.length,beforeSpecial.stats['一组'].administrative.length);
  await cmd('move',{personId:specialPersonId,targetGroup:null});s=await snapshot();assert.equal(s.states.find(state=>state.personId===specialPersonId).workingGroup,null);
  const person=s.people.find(p=>p.administrativeGroup==='一组'), id=person.id;
  const authorizationSummary=(await api(`capability/personnel/${id}/authorizations${suffix}`)).value;
  assert.equal(Object.values(authorizationSummary.counts).reduce((sum,value)=>sum+value,0),db.prepare("select count(*) as n from personnel_authorizations where person_id=? and coalesce(data_status,'active')='active' and authorization_status='有效'").get(id).n);
  const firstCategory=Object.entries(authorizationSummary.counts).find(([,count])=>count)?.[0],authorizationDetails=(await api(`capability/personnel/${id}/authorizations${suffix}&category=${firstCategory}`)).value;
  assert.equal(authorizationDetails.items.length,authorizationSummary.counts[firstCategory]);
  const projectName=authorizationDetails.items[0].projectName,personnelSearch=(await api(`personnel?q=${encodeURIComponent(projectName)}`)).value;
  assert.ok(personnelSearch.items.some(item=>item.personId===id),'人员列表应支持授权项目名称搜索');
  assert.throws(()=>db.prepare("insert into personnel_licenses(id,person_id,employee_no,license_no,license_type,is_valid,created_at,updated_at) values(?,?,?,?,?,'有效',?,?)").run(crypto.randomUUID(),id,'99999999','WRONG-ID','CAAC',new Date().toISOString(),new Date().toISOString()),/身份对应不一致/);
  assert.throws(()=>db.prepare("insert into capability_current_states(person_id,status,working_group,workspace,administrative_group,sort_index,record_id,updated_at) values('missing-person','ON_DUTY','一组',?,'一组',0,null,?)").run(workspace,new Date().toISOString()),/人员不存在或已失效/);
  // Duplicate record and irrelevant expiry dates never duplicate capability holders.
  const auth=db.prepare('select * from personnel_authorizations where person_id=? limit 1').get(id);
  const columns=Object.keys(auth),copy={...auth,id:crypto.randomUUID(),authorization_type:'duplicate-for-test',authorization_expires_at:'1900-01-01'};
  db.prepare('insert into personnel_authorizations('+columns.join(',')+') values('+columns.map(()=>'?').join(',')+')').run(...columns.map(k=>copy[k]));
  service.syncMaster();s=await snapshot();assert.deepEqual(s.matrix.map(p=>p.actual),initial.matrix.map(p=>p.actual));
  const request={operation:'move',personId:id,targetGroup:'二组',revision:s.revision,requestId:crypto.randomUUID()};
  const result=(await api('capability/commands'+suffix,request)).value;
  const moved=await snapshot();assert.deepEqual(moved.matrix.map(p=>p.administrative),s.matrix.map(p=>p.administrative));
  assert.equal(moved.stats['一组'].actual.length,s.stats['一组'].actual.length-1);assert.equal(moved.stats['二组'].actual.length,s.stats['二组'].actual.length+1);
  assert.ok(moved.supports.some(r=>r.person_id===id&&!r.ended_at));
  for(const p of s.matrix){const next=moved.matrix.find(q=>q.key===p.key),has=person.capabilities.some(c=>c.key===p.key);assert.equal(next.actual['一组'].length,p.actual['一组'].length-(has?1:0));assert.equal(next.actual['二组'].length,p.actual['二组'].length+(has?1:0));}
  await api('capability/commands'+suffix,request);assert.equal((await snapshot()).history.length,moved.history.length);
  await api('capability/commands'+suffix,{...request,requestId:crypto.randomUUID()},409);
  await cmd('compensate',{historyId:result.historyId});s=await snapshot();assert.ok(s.history.length>moved.history.length);assert.equal(s.states.find(p=>p.personId===id).workingGroup,'一组');
  const laneOrder=(snap,g)=>snap.states.filter(p=>p.status==='ON_DUTY'&&p.workingGroup===g).sort((a,b)=>a.index-b.index).map(p=>p.personId);
  assert.deepEqual(laneOrder(s,'一组'),laneOrder(initial,'一组'),'补偿应恢复原始相对位置');
  const beforeSort=s.matrix;await cmd('move',{personId:id,targetGroup:'一组',targetIndex:0});s=await snapshot();assert.deepEqual(s.matrix,beforeSort);
  await cmd('move',{personId:id,targetGroup:'二组'});await cmd('move',{personId:id,targetGroup:'三组'});assert.equal((await snapshot()).supports.filter(r=>r.person_id===id&&!r.ended_at).length,1);
  await cmd('status',{personId:id,kind:'TRAINING',label:'测试培训',startDate:today()});
  s=await snapshot();assert.equal(s.states.find(p=>p.personId===id).status,'TRAINING');assert.equal(s.states.find(p=>p.personId===id).workingGroup,null);
  assert.equal(s.supports.filter(r=>r.person_id===id&&!r.ended_at).length,0);
  await cmd('move',{personId:id,targetGroup:'四组'},409);
  await cmd('createDeploymentLocation',{name:'测试站点'});s=await snapshot();const testLocation=s.deploymentLocations.find(item=>item.name==='测试站点');assert.ok(testLocation);
  await cmd('status',{personId:id,kind:'DEPLOYED',deploymentLocationId:testLocation.id,startDate:today()},409);
  const record=s.records.find(r=>r.person_id===id&&r.phase==='ACTIVE');
  await cmd('end',{recordId:record.id,endDate:'2099-01-01'},400);
  await cmd('end',{recordId:record.id});s=await snapshot();assert.equal(s.states.find(p=>p.personId===id).workingGroup,'一组');
  // A same-location deployment handover is one atomic command and remains traceable.
  const [outgoingPerson,incomingPerson,duplicateIncoming]=s.people.filter(p=>p.id!==id&&p.administrativeGroup).slice(0,3);
  await cmd('createDeploymentLocation',{name:'交接站点'});s=await snapshot();const handoverLocation=s.deploymentLocations.find(item=>item.name==='交接站点');
  await cmd('status',{personId:outgoingPerson.id,kind:'DEPLOYED',deploymentLocationId:handoverLocation.id,startDate:today()});s=await snapshot();
  const outgoingRecord=s.records.find(r=>r.person_id===outgoingPerson.id&&r.kind==='DEPLOYED'&&r.phase==='ACTIVE');
  const beforeRejected=s.records.length;
  await cmd('replaceDeployment',{personId:incomingPerson.id,deploymentLocationId:testLocation.id,startDate:today(),replacesRecordId:outgoingRecord.id},409);
  assert.equal((await snapshot()).records.length,beforeRejected,'交接校验失败不得写入部分数据');
  await cmd('updateDeploymentLocation',{locationId:handoverLocation.id,name:'交接站点新名',reason:'验证固定ID交接'});
  await cmd('replaceDeployment',{personId:incomingPerson.id,deploymentLocationId:handoverLocation.id,startDate:today(),replacesRecordId:outgoingRecord.id});s=await snapshot();
  const incomingRecord=s.records.find(r=>r.person_id===incomingPerson.id&&r.replaces_record_id===outgoingRecord.id);
  assert.ok(incomingRecord);assert.equal(s.records.find(r=>r.id===outgoingRecord.id).end_date,today());
  assert.equal(s.states.find(state=>state.personId===outgoingPerson.id).status,'DEPLOYED');
  assert.equal(s.states.find(state=>state.personId===incomingPerson.id).status,'DEPLOYED');
  assert.ok(s.history.some(h=>h.type==='DEPLOYMENT_REPLACED'&&h.person_id===outgoingPerson.id));
  assert.ok(s.history.some(h=>h.type==='DEPLOYMENT_REPLACEMENT_CREATED'&&h.person_id===incomingPerson.id));
  assert.ok(db.prepare('pragma table_info(capability_status_records)').all().some(c=>c.name==='replaces_record_id'));
  assert.ok(db.prepare('pragma table_info(capability_status_records)').all().some(c=>c.name==='deployment_location_id'));
  assert.ok(db.prepare('pragma table_info(capability_status_records)').all().some(c=>c.name==='data_status'));
  assert.ok(db.prepare('pragma table_info(capability_status_records)').all().some(c=>c.name==='deletion_reason'));
  assert.equal(incomingRecord.deployment_location_id,handoverLocation.id);
  const afterHandover=s.records.length;
  await cmd('replaceDeployment',{personId:duplicateIncoming.id,deploymentLocationId:handoverLocation.id,startDate:today(),replacesRecordId:outgoingRecord.id},409);
  assert.equal((await snapshot()).records.length,afterHandover,'同一派驻记录只能建立一次接替关系');
  assert.throws(()=>db.prepare("insert into capability_status_records(id,person_id,workspace,kind,label,start_date,end_date,phase,remark,created_at,updated_at,replaces_record_id) values(?,?,?,?,?,?,?,?,?,?,?,?)").run(crypto.randomUUID(),duplicateIncoming.id,workspace,'TRAINING','非法交接',today(),null,'PLANNED','',new Date().toISOString(),new Date().toISOString(),outgoingRecord.id),/派驻交接关系无效|唯一/);
  await cmd('end',{recordId:outgoingRecord.id});await cmd('end',{recordId:incomingRecord.id});s=await snapshot();
  await cmd('updateStatus',{recordId:incomingRecord.id,deploymentLocationId:handoverLocation.id,startDate:incomingRecord.start_date,endDate:today(),remark:'历史修正',reason:'验证超级管理员历史修改'});s=await snapshot();assert.equal(s.records.find(r=>r.id===incomingRecord.id).remark,'历史修正');
  // Planned records can form a date-ordered A -> B -> C handover chain.
  await cmd('status',{personId:outgoingPerson.id,kind:'DEPLOYED',deploymentLocationId:handoverLocation.id,startDate:today()});s=await snapshot();
  const chainA=s.records.find(r=>r.person_id===outgoingPerson.id&&r.phase==='ACTIVE'&&r.deployment_location_id===handoverLocation.id);
  await cmd('replaceDeployment',{personId:incomingPerson.id,deploymentLocationId:handoverLocation.id,startDate:'2098-01-01',replacesRecordId:chainA.id});s=await snapshot();
  const chainB=s.records.find(r=>r.person_id===incomingPerson.id&&r.phase==='PLANNED'&&r.replaces_record_id===chainA.id);
  await cmd('replaceDeployment',{personId:duplicateIncoming.id,deploymentLocationId:handoverLocation.id,startDate:'2098-02-01',replacesRecordId:chainB.id});s=await snapshot();
  const chainC=s.records.find(r=>r.person_id===duplicateIncoming.id&&r.phase==='PLANNED'&&r.replaces_record_id===chainB.id);
  assert.ok(chainC);assert.equal(s.records.find(r=>r.id===chainA.id).end_date,'2098-01-01');assert.equal(s.records.find(r=>r.id===chainB.id).end_date,'2098-02-01');
  await cmd('deleteStatus',{recordId:chainB.id,reason:'验证计划链中节点安全删除'});s=await snapshot();assert.ok(!s.records.some(r=>r.id===chainB.id));assert.equal(db.prepare('select data_status from capability_status_records where id=?').get(chainB.id).data_status,'deleted');
  await cmd('deleteStatus',{recordId:chainC.id,reason:'验证计划状态安全删除'});await cmd('deleteStatus',{recordId:chainA.id,reason:'验证进行中状态安全删除'});s=await snapshot();assert.equal(s.states.find(state=>state.personId===outgoingPerson.id).status,'ON_DUTY');assert.ok(s.history.some(h=>h.type==='STATUS_SAFE_DELETED'&&h.person_id===outgoingPerson.id));
  await cmd('deleteDeploymentLocation',{locationId:handoverLocation.id,reason:'引用地点应转为停用'});s=await snapshot();assert.equal(s.deploymentLocations.find(item=>item.id===handoverLocation.id).status,'inactive');
  await cmd('setDeploymentLocationStatus',{locationId:handoverLocation.id,status:'active',reason:'恢复测试'});
  await cmd('createDeploymentLocation',{name:'未引用地点'});s=await snapshot();const unusedLocation=s.deploymentLocations.find(item=>item.name==='未引用地点');await cmd('deleteDeploymentLocation',{locationId:unusedLocation.id,reason:'未引用可删除'});s=await snapshot();assert.ok(!s.deploymentLocations.some(item=>item.id===unusedLocation.id));
  const other=s.people.find(p=>!p.administrativeGroup);assert.ok(other);
  await cmd('createOtherStatusOption',{name:'测试其他'});s=await snapshot();const otherOption=s.otherStatusOptions.find(item=>item.name==='测试其他');assert.ok(otherOption);
  await cmd('status',{personId:other.id,kind:'OTHER',label:'不能直接提交的自由文字',startDate:today()},400);
  await cmd('status',{personId:other.id,kind:'OTHER',otherStatusOptionId:'wrong-workspace-or-missing',startDate:today()},404);
  await cmd('status',{personId:other.id,kind:'OTHER',otherStatusOptionId:otherOption.id,startDate:today()});s=await snapshot();
  const otherRecord=s.records.find(r=>r.kind==='OTHER'&&r.person_id===other.id);assert.equal(otherRecord.other_status_option_id,otherOption.id);
  assert.equal(otherRecord.label_snapshot,'测试其他');
  await cmd('updateOtherStatusOption',{optionId:otherOption.id,name:'测试其他新名',reason:'核对目录改名'});s=await snapshot();
  assert.equal(s.records.find(r=>r.id===otherRecord.id).label,'测试其他新名');assert.equal(s.records.find(r=>r.id===otherRecord.id).label_snapshot,'测试其他');
  await cmd('setOtherStatusOptionStatus',{optionId:otherOption.id,status:'inactive',reason:'测试停用'},409);
  await cmd('setOtherStatusOptionStatus',{optionId:otherOption.id,status:'inactive',reason:'测试停用',confirmImpact:true});s=await snapshot();
  assert.equal(s.otherStatusOptions.find(item=>item.id===otherOption.id).status,'inactive');assert.equal(s.records.find(r=>r.id===otherRecord.id).label,'测试其他新名');
  await cmd('updateStatus',{recordId:otherRecord.id,otherStatusOptionId:otherOption.id,startDate:otherRecord.start_date,endDate:otherRecord.end_date,remark:'保留旧项'},200);
  await cmd('createOtherStatusOption',{name:'测试其他新名'},409);
  await cmd('deleteOtherStatusOption',{optionId:otherOption.id,reason:'已引用转停用',confirmImpact:true});s=await snapshot();assert.ok(s.otherStatusOptions.some(item=>item.id===otherOption.id));
  await cmd('createOtherStatusOption',{name:'未引用状态'});s=await snapshot();const unusedOther=s.otherStatusOptions.find(item=>item.name==='未引用状态');
  await cmd('deleteOtherStatusOption',{optionId:unusedOther.id,reason:'未引用可删除'});s=await snapshot();assert.ok(!s.otherStatusOptions.some(item=>item.id===unusedOther.id));
  await cmd('end',{recordId:s.records.find(r=>r.person_id===other.id&&r.phase==='ACTIVE').id});assert.equal((await snapshot()).states.find(p=>p.personId===other.id).workingGroup,null);
  await cmd('createDeploymentLocation',{name:'未来站点'});s=await snapshot();const futureLocation=s.deploymentLocations.find(item=>item.name==='未来站点');
  await cmd('status',{personId:id,kind:'DEPLOYED',deploymentLocationId:futureLocation.id,startDate:'2098-01-01'});s=await snapshot();assert.equal(s.states.find(p=>p.personId===id).status,'ON_DUTY');
  const planned=s.records.find(r=>r.person_id===id&&r.phase==='PLANNED');
  db.prepare('update capability_status_records set start_date=? where id=?').run(today(),planned.id);service.schedule();assert.equal((await snapshot()).states.find(p=>p.personId===id).status,'DEPLOYED');
  await cmd('end',{recordId:planned.id});
  s=await snapshot();const sim=structuredClone(s.states);sim.find(p=>p.personId===id).workingGroup='四组';
  await cmd('saveScenario',{name:'回归方案',states:sim,baseRevision:s.revision});
  assert.equal((await snapshot()).states.find(p=>p.personId===id).workingGroup,'一组');
  const bad=structuredClone(sim);bad.at(-1).status='TRAINING';const beforeInvalid=await snapshot();
  await cmd('applyScenario',{states:bad,baseRevision:beforeInvalid.revision},409);assert.deepEqual((await snapshot()).states,beforeInvalid.states);
  await cmd('applyScenario',{states:sim,baseRevision:beforeInvalid.revision});s=await snapshot();assert.equal(s.states.find(p=>p.personId===id).workingGroup,'四组');
  await cmd('applyScenario',{states:sim,baseRevision:beforeInvalid.revision},409);
  const config=structuredClone(s.config),key=config.priority[0];config.targets[key]={一组:0,二组:999,三组:0,四组:0};
  await cmd('config',{config});s=await snapshot();assert.ok(!s.alerts.some(a=>a.key===key&&a.group==='一组'));assert.ok(s.alerts.some(a=>a.key===key&&a.group==='二组'&&a.severity==='danger'));
  // Service checks permissions and full target scope, independently of disabled UI.
  const scoped=createCapabilityService({db,hasRbac:(a,p)=>a.permissions.includes(p),personnelAccess:{allows:(a,m,id)=>a.ids.includes(id)},audit:()=>{}});
  const reader={id:'reader',permissions:['capability.overview.view'],ids:[id]};
  assert.equal(scoped.snapshot(reader,workspace).people.length,1);
  assert.throws(()=>scoped.command(reader,workspace,'move',{requestId:crypto.randomUUID(),revision:s.revision,personId:id,targetGroup:'二组'}),e=>e.status===403);
  const allocator={...reader,permissions:['capability.overview.view','capability.allocation.view','capability.allocation.submit','capability.config.manage']};
  assert.throws(()=>scoped.command(allocator,workspace,'move',{requestId:crypto.randomUUID(),revision:s.revision,personId:id,targetGroup:'二组'}),e=>e.status===403);
  assert.throws(()=>scoped.command(allocator,workspace,'config',{requestId:crypto.randomUUID(),revision:s.revision,config}),e=>e.status===403);
  const ordinaryStatusManager={...reader,permissions:['capability.overview.view','capability.status.view','capability.status.manage']};
  assert.throws(()=>scoped.command(ordinaryStatusManager,workspace,'deleteStatus',{requestId:crypto.randomUUID(),revision:s.revision,recordId:record.id,reason:'不应允许'}),e=>e.status===403);
  assert.throws(()=>scoped.report(reader,workspace),e=>e.status===403);
  const report=(await api('capability/reports'+suffix)).value;assert.deepEqual(report.matrix,s.matrix);
  await api('capability/migration-preview'+suffix,{snapshot:{}},404);
  await cmd('migration',{snapshot:{}},400);
  assert.throws(()=>scoped.snapshot(reader,'unknown-workspace'),e=>e.status===403);
  // Two authenticated SSE clients receive committed changes; payload contains no personnel data.
  const ac1=new AbortController(),ac2=new AbortController();
  const streams=await Promise.all([ac1,ac2].map(ac=>fetch(base+'/api/capability/events',{headers:{cookie},signal:ac.signal}).then(r=>r.body.getReader())));
  await Promise.all(streams.map(r=>r.read()));await cmd('restore');
  for(const stream of streams){const {value}=await stream.read();const text=new TextDecoder().decode(value);assert.match(text,/"revision"/);assert.ok(!text.includes(person.name));}
  ac1.abort();ac2.abort();
  service.syncMaster();s=await snapshot();const preserved=s.states.find(p=>p.personId===id);
  const secondService=createCapabilityService({db,hasRbac:()=>true,personnelAccess:{allows:()=>true},audit:()=>{}});secondService.init();assert.deepEqual(secondService.snapshot(actor,workspace).states.find(p=>p.personId===id),preserved);
  const renameBefore=await snapshot();
  const historyBefore=JSON.stringify(db.prepare('select * from capability_history order by id').all());
  const {personnelAccess}=await import('../server.mjs');
  const firstTeam=db.prepare("select * from organization_units where code='TEAM-LINE-1'").get();
  personnelAccess.mutateOrganization(actor,'PUT',firstTeam.id,{name:'第一维修班',reason:'改名回归'});
  service.syncMaster();
  const renamed=await snapshot();
  assert.deepEqual(renamed.states,renameBefore.states);
  assert.deepEqual(renamed.matrix,renameBefore.matrix);
  assert.equal(JSON.stringify(db.prepare('select * from capability_history order by id').all()),historyBefore);
  assert.equal(renamed.lanes.find(l=>l.key==='一组').name,'第一维修班');
  assert.equal(renamed.people.find(p=>p.id===id).administrativeUnit,'第一维修班');
  await cmd('move',{personId:id,targetGroup:'二组'});
  await cmd('move',{personId:id,targetGroup:'一组'});
  assert.equal((await snapshot()).states.find(p=>p.personId===id).currentWorkingTeamId,firstTeam.id);
  const firstGroup=db.prepare("select * from organization_units where code='GROUP-LINE-2'").get();
  assert.throws(()=>personnelAccess.mutateOrganization(actor,'PUT',firstGroup.id,{name:firstGroup.name,maintenanceEligible:false,reason:'阻断测试'}),e=>e.status===409&&e.details.activeAllocations===4);
  secondService.init();
  assert.equal(secondService.snapshot(actor,workspace).lanes.find(l=>l.key==='一组').name,'第一维修班');
  db.prepare("update personnel set employment_status='离职' where id=?").run(id);service.syncMaster();
  assert.ok(!(await snapshot()).people.some(p=>p.id===id));assert.ok((await snapshot()).historicalPeople.some(p=>p.id===id));assert.ok((await snapshot()).history.some(h=>h.person_id===id));assert.ok(db.prepare('select count(*) as n from capability_history where person_id=?').get(id).n>0);
  console.log(JSON.stringify({ok:true,baselinePeople:initial.people.length,groups:GROUPS.map(g=>initial.stats[g].administrative.length),tests:'identity, dedupe, dual-matrix, sorting, support, compensation, status, atomic deployment handover, scheduler, atomic scenarios, targets, RBAC/scope, idempotency, concurrency, reports, two SSE clients, persistence',testDatabase:tmp},null,2));
} finally {server.closeAllConnections();await new Promise(r=>server.close(r));db.close();}
